#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: 이지형 그래픽스 프로그래머
url: 'http://leejh601.github.io'
lang: ko-KR

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/online-cv' 

description: A beautiful Jekyll theme for creating resume
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic teal oceanstale
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

collections:
  projects:
    output: true
    permalink: _projects/:name

analytics:
  provider: "google-gtag"

  google:
    tracking_id: "G-1GVDD78P94"


# Development Settings
port: 4000
host: 0.0.0.0
safe: false
