<<<<<<< HEAD
# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

url: "https://LeejH601.github.io"
title:		   "LEE JIHYUNG's PortPolio"
description: "Powered by Jekyll and GitHub Pages"
author:      "LEE JIHYUNG"
=======
theme: jekyll-theme-minimal
title: LEE JIHYUNG's homepage
description: Bookmark this to keep an eye on my project updates!
>>>>>>> parent of 9b54e07 (Portfolio Jekyll Theme 적용)
